##
## You provide this
##

FROM dirkcgrunwald/facerec:latest

EXPOSE 8501

RUN pip install streamlit redis jsonpickle

WORKDIR /srv

COPY GamesUplay.py /srv

COPY SessionState.py /srv

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN mkdir -p /root/.streamlit
RUN bash -c 'echo -e "\
[general]\n\
email = \"\"\n\
" > /root/.streamlit/credentials.toml'
RUN bash -c 'echo -e "\
[server]\n\
enableXsrfProtection = false\n\
enableCORS = false\n\
" > /root/.streamlit/config.toml'

CMD streamlit run GamesUplay.py